### ISSUE TITLE
ui-theme-uilightness 7.0.0-M5 Initializer.class contains setStripWicketTags(true);

### ISSUE THREAD

**Issue by greggulrajani** [sebfz1/wicket-jquery-ui#158]
Hello Sebfz1,

Trying to use this jar my unit tests fail due to  setStripWicketTags(true);

Thanks for the great port!
Greg

**Comment by sebfz1** [comment]
Hi Greg,

I will need some more context...

Having/checking `setStripWicketTags(true)` is not supposed to break test. I mean, if you check if wicket-tags are *not* stripped, then I guess it's a testing issue (in prod, wicket-tags *are* stripped).

Furthermore, this is required/mandatory to have stripped wicket-tags for certain widgets to work properly, some are using accessors like `ul > li` (dummy example), if there is a `wicket:container` in between, the widget will not work of course...

Please give me some more detail on your use case...

Thanks & best regards,
Sebastien

**Comment by greggulrajani** [comment]
Hello Sebastien,

In our code base we use <code>getWicketTester().getTagByWicketId("messages")<code> in a few places. When <code>setStripWicketTags(true)</code> is set to true all these methods return null.

Best
Greg

**Comment by martin-g** [comment]
This is expected.
With `setStripWicketTags(true)` Wicket removes also all `wicket:id` attributes.

**Comment by greggulrajani** [comment]
@martin-g exactly which is why setting wicket run settings during a component scan is a bit sneaky. Those settings should be managed by the end user not a dependency.
To me I would rather have the layout borked in dev mode and when I run the app in a prod mode the layout is correct..

Best
Greg

**Comment by sebfz1** [comment]
Hi Greg,

The issue is not related to `Initializer.class` specifically, in any case you will need to strip wicket tags if you are using jQuery UI integration - even in dev mode (and it is not related to wicket-jquery-ui specifically, I am sure others integrations have the same requirements). 
`Initializer.class` does it for you, but if you figure out to use you custom resource references, you will have to explicitly strip wicket tags in `MyApplication#init()` or you will have troubles with some components/widgets...

An easy solution (I did not test but I guess it will work) is to change the strip-wicket-tag flag at test time:

```java
WicketTester tester = new WicketTester();
tester.getApplication().getMarkupSettings().setStripWicketTags(false);
```

I understand it could be seen as a limitation, but I really can't change this because of how jQuery UI interact with the underlying HTML...

Hope this helps,
Sebastien.

**Comment by martin-g** [comment]
The same is valid for https://github.com/l0rdn1kk0n/wicket-bootstrap.

Wicket initializers are ran before MyApplication#init(), so it is possible for you as developer to override whatever 3rd party dependencies configure automatically.
The problem with `<wicket:xyz>` in the markup and JQuery UI/Bootstrap is that they break the CSS rules and thus your application has broken UI. I am sure you cannot live with that even in DEV mode.

**Comment by greggulrajani** [comment]
Thanks Sebastian,

I can see why you need to do this. Rewriting the jquery-ui.css to work around Wicket's dev mode does not sound like an entertaining task. Switching setStripWicketTags(false) in our wicket tester fixed our unit tests and no one in our team is to fussed about losing the extra markup anyway  (and we may have hit this issue as well) 
 
Thanks @martin-g  and @sebfz1 
-greg

**Comment by martin-g** [comment]
:+1:

**Comment by sebfz1** [comment]
You are welcome :)

> Rewriting the jquery-ui.css to work around Wicket's dev mode does not sound like an entertaining task

Nope, and even this would not be sufficient: the jquery-ui code itself uses jquery's selectors like `ul > li` to access dom element(s)...
