### ISSUE TITLE
KendoUI DateTimePicker sometimes does not change its internal format when deactivating timepicker

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#199]
Hi Sebastien,
I have a conversion bug here, but I'm not really sure, whats the core problem is.

It seems on deactivating the timepicker, on some circumstances internally it still uses date format 'hh.dd.yy HH:mm' instead of 'hh.dd.yy' (or other way around) and this leads into an conversion exception.

I created a quickstart, because I wasn't able to fix it.

Could you please have a look?

To reproduce it:
- enter the homepage
- change the allday checkbox
- click go
- change the allday checkbox
- click go
```
    Error while parsing datetime: date was '11.09.15' and time was '00:00'
    Error while parsing datetime: date was '11.09.15' and time was '00:00'
```

Otherway around (first change, the boolean Model to true, to let the timepicker be disabled on entering the page)

- then enter the homepage
- change the allday checkbox
- click go
- change the allday checkbox
- click go
```
    Error while parsing datetime: date was '11.09.15' and time was 'null'
    Error while parsing datetime: date was '11.09.15' and time was 'null'
```

https://www.dropbox.com/s/d7sdcal4togfzoo/AjaxDateTimePicker2.zip?dl=0

kind regards
Patrick

Update: had a bug... please make sure use AjaxDateTimePicker2.zip

**Comment by sebfz1** [comment]
Hi Patrick, I will have a look on monday (at the best). Could you please
push your quickstart in a repo instead of a zip please ?
Thanks a best regards
Seb

**Comment by Patrick1701** [comment]
Good morning Sebastien,
ok, added as project into my fork.

Also added you as collaborator. Will this work, or do I have to create a pull request?

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

The idea was just to have the quickstart code in a repo (that belongs to you) instead of a zip (because it is more convenient to me, and it is simpler if I want to push a solution). Here you mixed the quickstart with wicket-jquery-ui repo (the fork), it would have been cleaner to have a different repo (like `wicket-jquery-ui-issue-199` or `datetimepicker-issue` or whatever you want, you can create as many repo as you wish... No need to add me as collaborator, I can clone it directly, and if I need to send you the correction, I will send you a pull-request...

![newrepo](https://cloud.githubusercontent.com/assets/1717144/9845998/881f574a-5acf-11e5-98da-658a6a68e182.png)

Best regards :)
Sebastien

**Comment by Patrick1701** [comment]
Alright... understood... thanx :)

Are you able to work the way it is now or should I change it first? I'm asking because will leave the office next, because I don't feel well today... Not sure, if I'm back tomorrow or next week.... :-/

**Comment by sebfz1** [comment]
Don't worry Patrick, I will manage... Rest well :)
