### ISSUE TITLE
It is impossible to override feedback in the Wizard

### ISSUE THREAD

**Issue by solomax** [sebfz1/wicket-jquery-ui#201]
Hello Sebastien,

I would like to replace standard feedback of Wizard with my own one (I would like to use KendoUI feedback with button)
I guess currently it is impossible :(
Maybe some overridable method can be added to AbstractWizard to be able to to this?
Something like:

	protected FeedbackPanel newFeedbackPanel(final String id) {
		return /* any custom feedback here*/;
	}
	
Thanks in advance!

**Comment by sebfz1** [comment]
Hi Maxim,

Done. I am deploying snapshots versions (`6.20.2-SNAPSHOT` & `7.0.2-SNAPSHOT`), but since last releases the code may not be fully aligned on 6.x & 7.x.

So far the 7.x changelog looks like:

15a58ef (HEAD, origin/master, origin/HEAD, master) jQueryUI: added AbstractWizard#newFeedbackPanel; fixes #201 
AbstractWizard#getFeedbackPanel() now returns WebMarkupContainer
12773f1 Kendo UI: Reworking DataTable button (toolbar & command) 
 - CommandButton#match now takes the name as argument, not the text - **SILENT API BREAK**
 - changed signature of IDataTableListener.onClick(AjaxRequestTarget, String, List<String>) to IDataTableListener.onClick(AjaxRequestTarget, ToolbarButton, List<String>) 
 - removed DataTable#newToolbarClickAjaxBehavior 
 - renamed DataTable#newColumnAjaxBehavior to #newCommandAjaxBehavior 
 - renamed DataTableBehavior#newToolbarClickAjaxBehavior(IJQueryAjaxAware) to #newToolbarAjaxBehavior(DataTableBehavior behavior, ToolbarButton) 
 - renamed DataTableBehavior#newButtonAjaxBehavior to #newCommandAjaxBehavior 
 - changed visibility of CommandButton#getCSSClass() to public

0c561b9 Kendo UI: AutoCompleteTextField, restored converter & added Class<T> ctor's arg
e6588da Kendo UI: DataTable, reload now also resets by default
67d5a32 Kendo UI: added CheckBox Samples: Added KendoCheckPage & KendoCheckBoxPage
709fc41 Core: Added JQueryTemplate
e17b921 Kendo UI: Added AbstractAutoCompleteTextField#getChoices 
Kendo UI: AutoCompleteTextField, removed useless converter (type nevergiven to ctor)
6339aba Kendo UI: removed lazy.MultiSelect#convertValue, added #convertInput (there is no converter)
5a076e7 Kendo UI: removed non-functioning DropDownList template ability, use lazy.DropDownList instead - **API BREAK**
c007d2a Kendo UI: Added lazy.DropDownList, for a better support of template usage
be022ca Core: Added ChoiceModelBehavior#ctor with IJQueryTemplate Core: Added ITextRenderer#getFields 
Kendo UI: enhanced usage of datasource (AutoCompleteTextField, ComboBox, MultiSelect)
bf6c861 Kendo UI: Added KendoFeedbackPanel#refresh + enhancement
b0cc9d9 Kendo UI: Added ResponsiveAdapter
39bb13c Kendo UI: Updated local.DateTimePicker; #199
91e32ab Kendo UI: DateTimePicker, always gets a new converter; fixes #199
cc23f48 Kendo UI: Added WindowButton#isIndicating(), so 'submit' window-buttons are now indicating buttons (and disabled on click)
6b164a4 Core: Added ListUtils#exclude 
 - updated ChoiceModelBehavior$ChoiceModelRequestHandler#respond 
 - updated AutoCompleteChoiceModelBehavior$AutoCompleteChoiceModelRequestHandler#respond 

Kendo UI: ComboBox#newDataSource, use ListUtils#exclude; fixes #198

**Comment by solomax** [comment]
Thanks a lot!
will try to test ASAP

**Comment by solomax** [comment]
just have tried it
unfortunately there seems to be an issue: "[feedback]" placeholder is being displayed on the wizard :(

trying to use it as follows

	@Override
	protected WebMarkupContainer newFeedbackPanel(String id) {
		KendoFeedbackPanel feedback = new KendoFeedbackPanel("feedback", new Options("button", true));
		feedback.setEscapeModelStrings(false);
		return feedback;
	}

**Comment by solomax** [comment]
Additionally: is it possible not to close Wizard in onClick" method if Finish button is pressed?

**Comment by sebfz1** [comment]
Oops, correcting (and testing :P)...

**Comment by sebfz1** [comment]
> "[feedback]" placeholder is being displayed on the wizard

corrected

**Comment by sebfz1** [comment]
> is it possible not to close Wizard in onClick" method if Finish button is pressed?

Yes, but that's not the case yet. Are you sure you want this? Because it may lead to a (silent) api break...

**Comment by solomax** [comment]
Actually I'm using wizard to provide installer wizard functionality
And I need to display progress, then close the wizard

To avoid API break optional property OFF by default maybe introduced (or overridable getter method returning boolean)

**Comment by sebfz1** [comment]
Understood & agreed...

**Comment by solomax** [comment]
Thanks!

**Comment by solomax** [comment]
Perfect! Thanks!

**Comment by sebfz1** [comment]
I will deploy 7.0.2-SNAPSHOT later today...
I will try to align with wicket6.x asap (I'm almost sure cannot cherrypick,
at least one of the commits)

**Comment by solomax** [comment]
sure, I also can test only tomorrow, sitting at the airport now :)

**Comment by sebfz1** [comment]
Well... You are at the airport since a while now ! :/

**Comment by solomax** [comment]
I got connection in Moscow for 5 hours
found free wifi and power outlet, can do some wicket-jquery-ui testing :))))

**Comment by sebfz1** [comment]
Lucky me, lol ! ;)

**Comment by sebfz1** [comment]
Hi Maxim,

I've redeployed `6.20.2-SNAPSHOT` & `7.0.2-SNAPSHOT` yesterday evening. I will redeploy tonight with #204 fix...

Enjoy! :)
Sebastien.

**Comment by solomax** [comment]
Great, thanks a lot!
will test both :)

**Comment by solomax** [comment]
Just have tested 6.20.2-SNAPSHOT, everything seems to work
Do you have any plans for release date? :))

**Comment by sebfz1** [comment]
Hi Maxim,

Glad to read this!

Well bugfix-releases are outside wicket's release planning.... So I can do
it this WE.. ;)

Best regards,
Sebastien.

**Comment by solomax** [comment]
great!
Will wait for it!
Thanks a lot!

**Comment by solomax** [comment]
Hello Sebastien,
Can you please release 6.20.2 and 7.02, it is extremely hard to work with maven snapshots with ivy :(

**Comment by sebfz1** [comment]
Let me check my status and if I'm clean (what I think), I'll do it in a few
minutes... :)

**Comment by solomax** [comment]
I can see 7.0.2, Thanks!

**Comment by sebfz1** [comment]
6.20.2 is also released, it should appear in maven central soon... Enjoy! :)
