### ISSUE TITLE
Why does AbstractFormDialog set DialogFormSubmitter on form.getRootForm()

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#212]
Hi Sebastien,
I'm wondering why the method ```AbstractFormDialog.internalOnClick(...)``` delegates its DialogFormSubmitter to the root-form of the form, provided by the dialog implementation.

```
	@Override
	void internalOnClick(AjaxRequestTarget target, DialogButton button)
	{
		final Form<?> form = this.getForm(button);

		if (form != null)
		{
			form.getRootForm().onFormSubmitted(new DialogFormSubmitter(target));
...
		}
...
	}
```

Is there any special intention doing this?

I get some side-effects on updated models on using dialogs on page-wizards, because the wizard itself also provides a form to achieve form-updates on step-transitions.
(order submit issue of nested forms; outer-form->inner-form submit)

kind regards
Patrick

**Comment by Patrick1701** [comment]
Ok, found out, this is not the main reason for my side-effects, but I still have this question.

**Comment by sebfz1** [comment]
Hi Patrick,

The main reason is that it's the way it is handled in wicket core [1]

I guess the underlying reason of this, is that no children forms are allowed in html (and AFAIK, still not). Even Wicket allows this, children forms are replaced by divs and the logic is performed internally by Wicket.

To be a valid form-submission process, the form has to be posted (ie: `POST` + `submit()`) [2]. That's only possible from a form element - the root form [3]. From my understanding `form.getRootForm().onFormSubmitted` is used to match the form-submitter.

But since we are in an ajax scope, I *think* `form.onFormSubmitted` should be ok, event more because the user supplies the form, but has to be tested with severals combinations...

Hope this enlighten you! :)

Best regards,
Sebastien

[1] https://github.com/apache/wicket/blob/master/wicket-core/src/main/java/org/apache/wicket/ajax/form/AjaxFormSubmitBehavior.java#L171

[2] https://github.com/sebfz1/wicket-jquery-ui/blob/master/wicket-jquery-ui/src/main/java/com/googlecode/wicket/jquery/ui/widget/dialog/ButtonAjaxPostBehavior.java#L59

[3] https://github.com/apache/wicket/blob/master/wicket-core/src/main/java/org/apache/wicket/markup/html/form/Form.java#L547

**Comment by Patrick1701** [comment]
> Hope this enlighten you! :)

Ähm... maybeeee?! :flushed::laughing:

Ok... I think, yes.
Possibly, you can help me with my question I sent into the wicket user list.
My mail relates to this issue, and I run out of ideas to handle the current problem, I have.
:disappointed_relieved:

**Comment by sebfz1** [comment]
Hi Patrick,

I was writing you an answer but Sven just replied with a perfect answer I guess (I was thinking about something with `#modelChanged`, the time to double check my idea in the code... too late :p)

Please close the issue if we are done.

Best regards,
Sebastien.
