### ISSUE TITLE
Add implementation of JQueryUI Selectmenu

### ISSUE THREAD

**Issue by Patrick1701** [sebfz1/wicket-jquery-ui#214]
Hi Sebastien,
(just an issue to have a issue# for the commit)

kind regards
Patrick

**Comment by sebfz1** [comment]
Thanks again Patrick!
I did not test everything (when it is disabled for instance...)
And I added a `.css('vertical-align', 'middle')` by default

**Comment by Patrick1701** [comment]
Hi Sebastien,

> I did not test everything (when it is disabled for instance...)

I tested disabling. Normal- and Ajaxified... both worked.

___

> And I added a .css('vertical-align', 'middle') by default

Ah, perfect... I wasn't able to fix the alignment... and ran out of ideas.
This sound good...
___

I wasn't sure about your naming-conventions in the samples... hope it was ok, especially for the menu item.

best regards
Patrick

**Comment by sebfz1** [comment]
> I tested disabling. Normal- and Ajaxified... both worked.

Cool, thanks!

> Ah, perfect... I wasn't able to fix the alignment... and ran out of ideas.

I think the only solution was to use the `create` event and access the underlying `selectmenu-button` element, because somehow the widget instance points to the `select`, not the generated element... 

> I wasn't sure about your naming-conventions in the samples... hope it was ok, especially for the menu item.

Was good. As we discussed earlier, we choose the wicket component name, not the widget name for this implementation, so it is not easy to make this quickly understandable to the user. I changed like as figure out it is the best as of today! ;)
