### ISSUE TITLE
Kendo-UI fallback to the known locale

### ISSUE THREAD

**Issue by solomax** [sebfz1/wicket-jquery-ui#250]
Hello Sebastien,

Recently I have updated our application to set locale based on user language and country (previously it was language only)
So now we can have locale like it-US, wicket seems to work as expected with it
jquery-ui complains like this:
http://localhost:5080/openmeetings/wicket/resource/com.googlecode.wicket.ke…resource.KendoCultureResourceReference/cultures/kendo.culture.it-US.min.js 

Two questions here:
1) why *min.js is being loaded in DEVELOPMENT mode
2) Maybe it is possible to load known language file?

**Comment by sebfz1** [comment]
Hi Maxim,

1. `.min.js` are loaded in DEVELOPEMENT mode because only minified version are packaged. The reason is that `.js.map` files are available (packaged) so development files (ie: non-minified) are useless.

2. You can look against the `KendoCulture` enum to ensure the culture you are attempting to use exists in kendo-ui (and then that the underlying file/resource exists). Also by careful if you are using kendo localized messages, you may also verify against the `KendoMessage` enum.

Hope this helps,
Sebastien.

**Comment by sebfz1** [comment]
Forgot to mention, I recently updated `KendoCultureHeaderContributor` to dynamically use the Session's Locale  (by using the default KendoCultureHeaderContributor ctor).

So maybe you can override `Session#getLocale()` and check whether the kendo-ui culture is supported, and fallback to another Locale if not... Just an idea.

**Comment by solomax** [comment]
Maybe it would be possible to provide locale to KendoCultureHeaderContributor? Or add check inside it?
Not sure how good is idea to change application locale cause on of the components "don't like" the locale set ....

**Comment by Patrick1701** [comment]
Hi Sebastien, Hi Maxim,

Sebastien, I remember, we had a short discussion once, if ```Session.get().getLocale()``` is safe to call in ```KendoCultureHeaderContributor```.
I don't really know the reason, but we decided to pass the local static via ctor.
(will try to find the thread, where we discussed)

I also have this issue... currently I'm not using ```KendoCultureHeaderContributor``` anymore because its too static.
I use ```KendoCultureHeaderItem(Session.get().getLocale())``` putting it manually to the HeaderItems of my pages.

Patrick

**Comment by solomax** [comment]
@Patrick1701 Will create safe Locale to KendoCulture transformation
Thanks for the pointer!

**Comment by sebfz1** [comment]
@Patrick1701,

Passing `Session.get().getLocale()` as the `KendoCultureHeaderContributor` ctor arg is not safe, that's right.  However, calling `Session.get().getLocale()` at `#renderHead` time is safe. That's what's happening if you do not supply argument to `KendoCultureHeaderContributor` [1]. This could replace your manual call to `KendoCultureHeaderItem(Session.get().getLocale())` I guess

@solomax ,

I will try to find out a way for fallback culture in case the specified culture (or session's culture) is not supported

[1] https://github.com/sebfz1/wicket-jquery-ui/blob/master/wicket-kendo-ui-culture/src/main/java/com/googlecode/wicket/kendo/ui/KendoCultureHeaderContributor.java#L78

**Comment by solomax** [comment]
I was planned to create static Set of all cultures supported and fallback to Session.get().getLocale().getLanguage(), and if this one is also absent to Locale.EN
I can share the code

**Comment by Patrick1701** [comment]
@sebfz1 

> However, calling Session.get().getLocale() at #renderHead time is safe.

Ok, then we could add a default ctor to the ```KendoCultureHeaderContributor```, and renderHead could decide, if the locale member is null, we use ```Session.get().getLocal()``` as fallback.

What do you think?

**Comment by solomax** [comment]
Here is the simple helper:

```
public class KendoCultureHeaderItem {
	private static Set<String> CULTURES = new HashSet<>();
	static {
		for (KendoCulture c : KendoCulture.values()) {
			CULTURES.add(c.toString());
		}
	}

	public static JavaScriptHeaderItem get() {
		Locale l = WebSession.get().getLocale();
		String culture = l.toLanguageTag();
		if (!CULTURES.contains(culture)) {
			culture = l.getLanguage();
			if (!CULTURES.contains(culture)) {
				culture = Locale.ENGLISH.getLanguage();
			}
		}
		return JavaScriptHeaderItem.forReference(new KendoCultureResourceReference(culture));
	}
}
```

**Comment by Patrick1701** [comment]
Ah, didn't see the code snippet.
( Race-Condition ;-) )

**Comment by solomax** [comment]
Yep, It's first prototype :)

**Comment by sebfz1** [comment]
@Patrick1701 

> Ok, then we could add a default ctor to the KendoCultureHeaderContributor, and renderHead could decide, if the locale member is null, we use Session.get().getLocal() as fallback.

So, you are suggesting that the culture/locale supplied to `KendoCultureHeaderContributor` is the fallback, and that the Session's Locale is always taken into account if valid?

@solomax 

Thanks for the code snippet :)

**Comment by sebfz1** [comment]
@Patrick1701 

> Ok, then we could add a default ctor to the KendoCultureHeaderContributor, and renderHead could decide, if the locale member is null, we use Session.get().getLocal() as fallback.

Well, reading your comment again, I guess I understood the opposite, lol! :)
Actually what you describe is what the code actually does! :)

**Comment by sebfz1** [comment]
@Patrick1701 

I think you was referring to this thread: https://github.com/sebfz1/wicket-jquery-ui/issues/222 (I think I can close it now...)

**Comment by solomax** [comment]
@sebfz1 here is the current helper: https://github.com/apache/openmeetings/blob/3.1.x/openmeetings-web/src/main/java/org/apache/openmeetings/web/common/KendoCultureHeaderItem.java, seems to work as expected

**Comment by sebfz1** [comment]
@solomax thanks for this, I may use it for inspiration :)
However, I think it only includes the culture file ; I do not see where it sets the culture for the kendo-ui widget, like:

```javascript
 <script type="text/javascript" id="kendo-culture">
 	kendo.culture('fr-FR');
 </script>
```

**Comment by solomax** [comment]
It is later being used like this:

```
	@Override
	public void renderHead(IHeaderResponse response) {
		super.renderHead(response);
		response.render(KendoCultureHeaderItem.get());
	}
```

This helper can be integrated into
```
new KendoCultureResourceReference(Locale)
```

**Comment by sebfz1** [comment]
I do see that `KendoCultureHeaderItem#get()` return the `HeaderItem` for `KendoCultureResourceReference` (the resource file, containing the culture info, format, etc), but the kendo culture variable still need to be initialized in the page, like it's done here:

https://github.com/sebfz1/wicket-jquery-ui/blob/ab7d16751b728aeb6a6652f7554861bdff743b54/wicket-kendo-ui-culture/src/main/java/com/googlecode/wicket/kendo/ui/KendoCultureHeaderItem.java#L70

I will try to make the change over the WE...

**Comment by sebfz1** [comment]
Additionally, there is 2 strategies for `KendoCultureHeaderContributor`

`1a.` If the culture is specified, we take it. No session's locale involved, no fallback
`1b.` If the culture is *not* specified, we take the session's locale. If invalid, fallback to a valid specified culture

`2.` We take the session's locale as the culture. If invalid, the fallback is the valid culture specified in the ctor. Default ctor means fallback is `EN`

I like the `#2`...
I am figuring out that the app would need to use a user session locale which is not necessary reflected in to kendo's widgets... That's why I would like to integrate this strategy/change in `KendoCultureHeaderContributor` only, so `KendoCultureHeaderItem` would allow a thiner control...

WDYT?

**Comment by solomax** [comment]
I actually have created my helper to implement `#2`, I'll drop it as soon as `KendoCultureHeaderContributor` will be improved :)

**Comment by sebfz1** [comment]
Consider it done! :)

**Comment by solomax** [comment]
Thanks a lot Sebastien :)

**Comment by sebfz1** [comment]
Hi Maxim,

While implementing this change, I've slightly changed my mind...
Here are the strategies.

For `KendoCultureHeaderContributor`:
- If the culture is specified in the ctor it will be used, disregarding the Session's Locale. This will prevent any silent API break.
- If the culture is *not* specified (default ctor), the Session's Locale *culture* will be used. If that culture is invalid then the Session's Locale *language* will be used as fallback.
- There is no fallback to English. First because there is fairly no chance that the fallback *language* is invalid. And even in that case (the user/dev specified 'xx' as the language for instance), the HeaderContributor will not be rendered providing a natural fallback to default widget's culture/language.

For `KendoMessageHeaderContributor`

It uses the same strategy except that there is no fallback to Session's Locale *language* because it is not supported (only cultures).

I've deployed snapshots (`8.0.0-SNAPSHOT`, `7.5.1-SNAPSHOT`, `6.25.1-SNAPSHOT`), so you can test it :).

Best regards,
Sebastien.

**Comment by Patrick1701** [comment]
@sebfz1 Hi Sebastien... concerning:

> It uses the same strategy except that there is no fallback to Session's Locale language because it is not supported (only cultures).

I think, this should work:
```new KendoMessageHeaderItem(LocaleUtils.getLangageCode(UserSession.get().getLocale()))```

What do you think?

Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Yes, it would work: but it will take the culture info from the Locale (ie: language + country).

What I mean is that message files are only available for culture, not just language like kendo-culture provides. That's why we could make a fallback to "language file" for KendoCulture, but not for KendoMessage...

Kendo culture files:
https://github.com/sebfz1/wicket-jquery-ui/tree/master/wicket-kendo-ui-culture/src/main/resources/com/googlecode/wicket/kendo/ui/resource/cultures

Kendo message files:
https://github.com/sebfz1/wicket-jquery-ui/tree/master/wicket-kendo-ui-culture/src/main/resources/com/googlecode/wicket/kendo/ui/resource/messages

Best regards,
Sebastien

**Comment by solomax** [comment]
@sebfz1 I'll try to check ASAP, most probably tomorrow

**Comment by sebfz1** [comment]
@solomax 

I've added the following helper methods:
- `KendoCultureHeaderItem.of(Locale)`, `KendoCultureHeaderItem.of(String...)`
- `KendoMessageHeaderItem.of(Locale)`, `KendoMessageHeaderItem.of(String...)`

`KendoCultureHeaderItem.of(Locale)` provides a fallback to the *language* in case of the *culture* is not found.

If you agree with this change, we will kindly ask @martin-g to deploy a snapshot [1] because I'm not able to do it during the week... :/)

Best regards,
Sebastien

[1]  from master branch (ie 7.x): `mvn clean deploy -P snapshot`

**Comment by solomax** [comment]
Thanks a lot! This is exactly what I need :)

**Comment by sebfz1** [comment]
@martin-g, would it be possible for you to deploy a snapshot whenever you can this week ? Thanks a lot in advance ! :)

**Comment by martin-g** [comment]
Which branch ? All ?

**Comment by martin-g** [comment]
OK. Now I read above ...

**Comment by sebfz1** [comment]
Only master, thats fine! :)

**Comment by martin-g** [comment]
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57:08 min

Yey!

**Comment by sebfz1** [comment]
Thanks a million, Martin !!! :)
